### ISSUE TITLE
Cache directory creation failure

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-file-page-cache#11]
Hi!

I get 

```
Failed to create cache directory /wp-content/cache/o10n/page-cache/14/79/21/
Failed to create directory /wp-content/cache/o10n/page-cache/14/79/21/ Error: mkdir(): Permission denied
```

although the parent directory 79 exists and the permissions are correct.

It would be helpful, if these errors shown when entering one of the optimization plugins would contain the module where the error occured and a timestamp when it happened (use server time).  That would help a lot to track the reason.

Is there a logfile written for such errors?

**Comment by optimalisatie** [comment]
Thank you for your suggestions!

The WPO Plugins are a quickly setup brigde between our old Above The Fold Optimization plugin and a planned Advanced Optimization plugin. The new technologies from the Advanced Optimization plugin were cut into individual optimization plugins/modules to form the "WPO plugin collection".

The error handling component was quickly added and was planned to be redone/improved later. 

The current implementation already provides a PHP [debug backtrace](http://php.net/manual/en/function.debug-backtrace.php) when using `O10N_DEBUG` in `wp-config.php`. We were planning to create a more sophisticated error handling system that supports error monitoring services such as Sentry, Airbrake, OverOps, Raygun and others. 

https://blog.takipi.com/the-complete-guide-to-error-tracking-tools-rollbar-vs-raygun-vs-sentry-vs-airbrake-vs-bugsnag-vs-overops/

We already added a unique innovation in which PHP errors are displayed in the browser console when using `O10N_DEBUG`. 

The plugin uses modern error handling based on PHP Exceptions. This means that if anything within the plugin or PHP fails, it will be reported in the admin (just on the optimization admin pages, not global). It also means that the plugin will be able to continue and complete a optimization if just a tiny part fails, or to allow a website to fall back to a non-optimized version.

![image](https://user-images.githubusercontent.com/8843669/41180460-a03ca1a4-6b6e-11e8-8cbb-599415311831.png)

### PHP Exceptions

A unique feature of the WPO plugins is that it uses PHP Exceptions that are logged to the WPO plugin admin so that you have a clear view if anything goes wrong. It also enables a website to remain usable if the WPO plugin (or parts of it) fail.

> ### [Why WP_Error Sucks](https://journal.rmccue.io/165/why-wp_error-sucks/)
> As anyone who has worked with WordPress knows, WordPress supported PHP 4 for a long time, even after many other projects had switched. The advantage of this was supporting significantly more hosts, with most PHP 5-only features either not being needed or being easy to reimplement.
> 
> One of the new features added to PHP in PHP 5 was exception handling... 
> 
> https://journal.rmccue.io/165/why-wp_error-sucks/

### Cross Browser javascript testing

We were also planning a unique cross browser javascript bug testing solution. Services such as CrossBrowserTesting.com and BrowserStack.com still do not support cross-browser testing of javascript issues. CrossBrowserTesting.com has communicated to be very interested in the feature but since the solution still does not exist, it seems difficult (costly) to realize in a "service".

For Artificial Intelligence based optimization automation it would be essential to know if a optimization causes javascript issues in for example iPhone 4 with browser Firefox, so that it can fine tune the settings for iPhone 4 users automatically. The javascript bug testing solution would need to be a sort of sensor for the optimization AI (an API). Also for this aspect the plugin would need to have an efficient error handling solution.

For now these innovations are on hold. The CEO of our company (@strayangelfilms) is currently working on finding a new future / funding / partner for the technology.
